version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  target-branch: development
  reviewers:
  - joshuapbritz
  assignees:
  - joshuapbritz
  labels:
  - enhancement
