# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    working_directory: ~/project
    docker:
      # specify the version you desire here
      - image: circleci/node:11.7-browsers
    steps:
      - checkout

      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # - run:
      #     name: Linting
      #     command: npm run lint

      # - run:
      #     name: Testing
      #     command: yarn test

      - run:
          name: Build
          command: yarn build
  deploy:
    working_directory: ~/project
    docker:
      # specify the version you desire here
      - image: circleci/node:11.7-browsers

    steps:
      - checkout
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - run: yarn global add parcel-bundler

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build
          command: yarn build

      - run:
          name: Deploy Master to Firebase
          command: yarn deploy:ci:prod
  deploy_staging:
    working_directory: ~/project
    docker:
      # specify the version you desire here
      - image: circleci/node:11.7-browsers

    steps:
      - checkout
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - run: yarn global add parcel-bundler

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build
          command: yarn build

      - run:
          name: Deploy Master to Firebase
          command: yarn deploy:ci:staging

workflows:
  version: 2

  build_and_deploy:
    jobs:
      - test
      - deploy_staging:
          requires:
            - test
          filters:
            branches:
              only: development
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
